### ISSUE TITLE
Заголовок H1

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#1]
На роль заголовка первого уровня на данном сайте очень хорошо подходит фраза в шапке сайта "Интернет-магазин строительных материалов и инструментов для ремонта". Соответственно, эту строку надо удалить:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L38

Однако в целом ты права, не во всех макетах такое, иногда дизайнер не прорисовывает главный заголовок и его действительно приходится прятать

**Comment by limasam** [comment]
Исправила этот момент, удалила ту строку и сделала так:
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L12-L16

**Comment by Morfey216** [comment]
Не нужно в разметке писать фразу в несколько строк, это всё равно бесполезно - браузер соберет такой вариант в одну строку

То есть такой код
> https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L12-L16

будет выглядеть так:
https://gyazo.com/2c4aed15ac089a787b54a873b3f42213

**Comment by limasam** [comment]
Сделано:
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/index.html#L12
