### ISSUE TITLE
Интерактивные элементы

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#10]
Этот элемент должен быть кнопкой
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L259
Размечаем тегом `button `и внутри прописываем вместо буквы "х" слово Закрыть

**Comment by limasam** [comment]
Добавила:
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/index.html#L253

**Comment by Morfey216** [comment]
Все кнопки "Закрыть" абсолютно одинаковы по стилям, классы у них должны быть тоже одинаковы

**Comment by limasam** [comment]
Исправлено:
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/index.html#L269
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/index.html#L274
