### ISSUE TITLE
Имена классов

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#11]
Вначале не хотел выписывать эту ошибку до момента работы со стилями, но вижу, что лучше исправить сейчас...
Классы чаще всего используются для связи элемента со стилями, поэтому и выбираются в первую очередь по стили. Например, если два разных элемента стилизуются одинаково, то классы у них совпадают. Например, кнопки пагинации совпадают по стилизации
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/catalog.html#L149-L160
Следовательно - основной (базовый) класс у них должен быть один и тот же. Например "pagination-item"

Или здесь: https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/catalog.html#L19-L20
Пункты стилизованы одинаково...

**Comment by limasam** [comment]
Сделала:
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/catalog.html#L183-L194

И тут тоже:
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/catalog.html#L17-L18

А еще исправила опечатку: 
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/catalog.html#L227

И добавила элементы:
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/catalog.html#L162-L171
