### ISSUE TITLE
Разметка всех элементов

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#12]
Не увидел у тебя в разметке кнопочек "По возрастанию" и "По убыванию" в сортировке на странице каталога
И этого модального окна на главной: https://gyazo.com/921ee60f1b5fce0351c6341180771c30

**Comment by limasam** [comment]
Модальное окошко добавила:
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/index.html#L291-L296
И кнопочки тоже)
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L122-L127

**Comment by Morfey216** [comment]
1. https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/index.html#L292
Эта фраза больше похожа на сообщение, т.е. параграф, а не заголовок. А вот к заголовку больше подойдет "Добавление товара в корзину"

2. https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L123
Я уже писал раньше: либо aria-label, либо текст ссылки. Двойное использование избыточно

3. Эти кнопочки имеет смысл выделить в отдельный список, так как и структурно и логически эта группа отличается от соседней

**Comment by limasam** [comment]
1.  https://github.com/limasam/technomart/blob/39a2aa868588140d75722172664d62aeb6c5f734/index.html#L292-L293
2-3. https://github.com/limasam/technomart/blob/39a2aa868588140d75722172664d62aeb6c5f734/catalog.html#L123-L130

**Comment by Morfey216** [comment]
По второму пункту... Вроде как и сделала, однако есть нюанс ))
http://joxi.ru/n2Y3PKaHkq1war

Может, всё-таки лучше прописать текстом?

**Comment by limasam** [comment]
https://github.com/limasam/technomart/blob/53974d95b030393af2e83b0558bcb7142b36a7d4/catalog.html#L124-L129
