### ISSUE TITLE
Атрибуты кнопки

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#13]
У тега `button `нужно прописывать атрибут `type`. Всегда.
https://github.com/limasam/technomart/blob/f76eb15692f6bfccd83f1fc00a66a6b3b3e68a7c/index.html#L284

**Comment by limasam** [comment]
Подправила
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L288
