### ISSUE TITLE
Атрибуты формы

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#14]
1. У тега form важно правильно указывать `method`. Если наша задача - просто передать параметры (то есть мы не передаем ничего в базу), то подойдет метод `get` https://github.com/limasam/technomart/blob/f76eb15692f6bfccd83f1fc00a66a6b3b3e68a7c/index.html#L10-L12
2. Если поля формы имеют тип `radio`, то необходимо соблюсти два условия: а) указать одинаковый `name` для группировки нескольких полей, б) указать атрибут `value` с прописанным значением, иначе сервер не поймет, какое именно поле выбрал пользователь https://github.com/limasam/technomart/blob/f76eb15692f6bfccd83f1fc00a66a6b3b3e68a7c/catalog.html#L97-L104
3. Значение атрибута `name` у чекбоксов, наоборот, повторяться не должно https://github.com/limasam/technomart/blob/f76eb15692f6bfccd83f1fc00a66a6b3b3e68a7c/catalog.html#L73
https://github.com/limasam/technomart/blob/f76eb15692f6bfccd83f1fc00a66a6b3b3e68a7c/catalog.html#L81

**Comment by limasam** [comment]
В форме подправила:
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L10-L12
И радиокнопки:
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L97-L104
И остальное тоже:
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L73
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L81
