### ISSUE TITLE
Доступность

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#15]
Интерактивные элементы должны быть однозначно подписаны. Например, поле формы можно подписать либо через тег `label`, либо через атрибут` aria-label`. Здесь же вообще форма, состоящая из одного поля, ни легенды, ни заголовка, ни подписи не предусмотрено
https://github.com/limasam/technomart/blob/f76eb15692f6bfccd83f1fc00a66a6b3b3e68a7c/index.html#L11

**Comment by limasam** [comment]
Сделано:
https://github.com/limasam/technomart/blob/1f68946ac8d809f3925ba76e234feb98e9111492/catalog.html#L11
