### ISSUE TITLE
Тег br

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#2]
С тегом `<br>` нужно быть очень аккуратной, многие задачи, где кажется, что он нужен, можно решить без него.
Здесь он не нужен:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L15-L17
И здесь:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L159-L160
И здесь:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L188-L191

И еще во многих местах )))
Сверстай лучше вначале без `br`, а если при стилизации уж никак не получится добиться нужного вида, только тогда добавишь

**Comment by limasam** [comment]
Вроде поменяла везде, но могла что-то упустить)
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L12-L16

**Comment by Morfey216** [comment]
В этом месте точно не нужно
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L156

**Comment by limasam** [comment]
Исправлено:
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/index.html#L152
