### ISSUE TITLE
Оформление ссылок

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#3]
1. На странице не должно быть циклических ссылок, то есть ссылок, которые ведут на эту же страницу.
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L27
Такая ссылка оформляется так: `<a>Главная</a>`, т.е. без `href`

2. Если адрес ссылки неизвестен, то в `href` вместо адреса указывают заглушку `#` (решетку)
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L30-L33

**Comment by limasam** [comment]
1. Убрала циклические ссылки: 
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L25
2. Исправила ссылки с неизвестным адресом:
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L28-L31

**Comment by Morfey216** [comment]
На странице каталога надо поправить: ссылки на каталог должны быть неактивны, но появляется href на главную
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/catalog.html#L28
Логотип тоже должен вести на главную
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/catalog.html#L9
То же самое в меню футера
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/catalog.html#L187

**Comment by limasam** [comment]
Доделала:
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/catalog.html#L9-L11
И это тоже:
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/catalog.html#L26
