### ISSUE TITLE
Разметка номера телефона и почты

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#4]
Номер телефона и адрес почты нужно размечать ссылками
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L19
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L247
Как это правильно сделать, можешь почитать здесь: 
http://htmlbook.ru/samhtml/ssylki/ssylka-na-adres-elektronnoy-pochty
и здесь
https://guruweba.com/web/ssylki-mailto-i-tel-na-pochtu-i-nomer-telefona/

**Comment by limasam** [comment]
Все почитала. Все исправила:
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L17
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L244

**Comment by Morfey216** [comment]
Здесь еще
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L218

**Comment by limasam** [comment]
Есть:
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/index.html#L212
