### ISSUE TITLE
Физическое форматирование текста

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#5]
Физическое форматирование текста применяется совсем не часто, обычно это делают через стили. Иначе могут появляться такие грубые ошибки, как эта:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L250

Здесь как раз подходит `span`, который позже застилизуется как надо

**Comment by limasam** [comment]
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L247
