### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#6]
Отступы при вложенности тегов должны соблюдаться везде!
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L253-L255

**Comment by limasam** [comment]
Исправила и заодно добавила блок для модального окна:
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L264-L266
