### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#7]
В данном макете логотип намного экономичнее будет прописать просто текстом
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L10

**Comment by limasam** [comment]
А такой вариант возможен?
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L9

**Comment by Morfey216** [comment]
В футере забыла
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L214-L216

**Comment by limasam** [comment]
👌🏻
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/index.html#L210

**Comment by Morfey216** [comment]
А страницу каталога кто исправлять будет?
https://github.com/limasam/technomart/blob/bf7739cad6530afd6a5e958e67bd8c352e8ef780/catalog.html#L9-L11

**Comment by limasam** [comment]
Я буду исправлять)
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/catalog.html#L9

**Comment by Morfey216** [comment]
Ну как так, Александра?
https://github.com/limasam/technomart/blob/84a459930a81e6db6fc18640ecfc2a68e2566755/catalog.html#L210-L212

**Comment by limasam** [comment]
Надеюсь, это уже конец))
https://github.com/limasam/technomart/blob/16e440b68e98b387f75631708be1cc84aa252c33/catalog.html#L210
