### ISSUE TITLE
Вложенность заголовков

### ISSUE THREAD

**Issue by Morfey216** [limasam/technomart#8]
Иерархия заголовков должна соблюдаться строго, т.е., например, внутрь блока с заголовком H2 можно вкладывать только H3 и т.д.
Здесь у тебя H2 https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L40
А здесь уже должен быть H3
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L69

Ну и уже попутно, чтоб не выносить в отдельную ошибку... Это тоже заголовки:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/index.html#L45
И здесь:
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/catalog.html#L58
https://github.com/limasam/technomart/blob/238823c15dc78a840c0a5b22447de07227f4d1fb/catalog.html#L85

**Comment by limasam** [comment]
Подправила:
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/index.html#L66
И здесь:
https://github.com/limasam/technomart/blob/0df7521614a84e2f585869d760c3cba03cbc7575/catalog.html#L82
